#!/bin/bash

# NOTE: set -o pipefail is needed to ensure that any error or failure causes the whole pipeline to fail.
# Without this specification, the CI status will provide a false sense of security by showing builds
# as succeeding in spite of errors or failures.
set -eo pipefail

ABBREV='<ABBREV>'

echo '##########################'
echo "BEGIN $ABBREV-user actions"
echo '##########################'

echo '------------------------------------------------------------------'
echo "Setting /home/`whoami`/.bashrc to automatically record login times"
echo "echo '------------------'" >> /home/`whoami`/.bashrc
echo "echo 'Welcome to Docker!'" >> /home/`whoami`/.bashrc
echo 'DATE=`date +%Y_%m%d_%H%M_%S -u`' >> /home/`whoami`/.bashrc
echo 'echo $DATE >> /home/`whoami`/timestamp.txt' >> /home/`whoami`/.bashrc
echo 'cat /etc/motd' >> /home/`whoami`/.bashrc
echo "echo '------------------------------'" >> /home/`whoami`/.bashrc
echo 'echo "cat /home/`whoami`/timestamp.txt"' >> /home/`whoami`/.bashrc
echo 'cat "/home/`whoami`/timestamp.txt"' >> /home/`whoami`/.bashrc
echo 'cd /home/`whoami`/shared' >> /home/`whoami`/.bashrc

echo '#############################'
echo "FINISHED $ABBREV-user actions"
echo '#############################'
