#!/bin/bash

# NOTE: set -o pipefail is needed to ensure that any error or failure causes the whole pipeline to fail.
# Without this specification, the CI status will provide a false sense of security by showing builds
# as succeeding in spite of errors or failures.
set -eo pipefail

ABBREV='<ABBREV>'

echo '###########################'
echo "BEGIN $ABBREV sanity checks"
echo '###########################'

echo '-------------------'
echo 'cat /etc/os-release'
cat /etc/os-release

echo '--------------------------------'
echo 'cat /home/`whoami`/timestamp.txt'
cat /home/`whoami`/timestamp.txt

echo '------'
echo 'whoami'
whoami

echo '-----------'
echo 'sudo whoami'
sudo whoami

echo '--------------'
echo 'sudo --version'
sudo --version

echo '--------------'
echo 'nano --version'
nano --version

echo '##############################'
echo "FINISHED $ABBREV sanity checks"
echo '##############################'
