#!/bin/bash

# NOTE: set -o pipefail is needed to ensure that any error or failure causes the whole pipeline to fail.
# Without this specification, the CI status will provide a false sense of security by showing builds
# as succeeding in spite of errors or failures.
set -eo pipefail

echo '-------------------'
echo 'BEGIN finalize-user'
echo '-------------------'

DATE=`date +%Y_%m%d_%H%M_%S -u`
echo "Build Date: $DATE" >> /home/`whoami`/timestamp.txt

echo "cat /home/`whoami`/timestamp.txt"
cat /home/`whoami`/timestamp.txt

echo '----------------------'
echo 'FINISHED finalize-user'
echo '----------------------'
