name: Build

on:
  pull_request:
  push:
  schedule:
    - cron: '17 7,19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        CODE_NAME: ['bookworm', 'trixie']
        
    env:
      SUITE: ${{ matrix.CODE_NAME }}

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: bash build-ci.sh
