name: Build

on:
  pull_request:
  push:
  schedule:
    - cron: '13 7,19 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        CODE_NAME: ['bookworm', 'trixie', 'sid']
        
    env:
      SUITE: ${{ matrix.CODE_NAME }}

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: bash build-ci.sh

      - name: Test Docker image
        run: bash test.sh

      - name: Log in to the Docker container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ github.ref == 'refs/heads/main' }}

      - name: Publish the Docker image
        run: source variables.sh && docker push $DOCKER_IMAGE:latest
        if: ${{ github.ref == 'refs/heads/main' }}

      - name: Delete old containers
        uses: snok/container-retention-policy@v2
        with:
          image-names: image-debian-*-min-stage1
          cut-off: A week ago UTC
          account-type: org
          org-name: rubyonracetracks
          keep-at-least: 1
          untagged-only: true
          token: ${{ secrets.SPECIAL_TOKEN }}
        if: ${{ github.ref == 'refs/heads/main' }}

      - name: Log out of the Docker container registry
        run: docker logout ghcr.io
        if: ${{ github.ref == 'refs/heads/main' }}
